-- =============================================================================
-- Migration: Batch Management System
-- File 11: Create batch tables (idempotent)
-- =============================================================================

-- Drop and recreate tables to ensure clean state
DROP TABLE IF EXISTS lms_admin.batch_lesson_releases CASCADE;
DROP TABLE IF EXISTS lms_admin.batch_classes CASCADE;
DROP TABLE IF EXISTS lms_admin.batch_courses CASCADE;
DROP TABLE IF EXISTS lms_admin.batch_members CASCADE;
DROP TABLE IF EXISTS lms_admin.batches CASCADE;

-- Create batches table
CREATE TABLE lms_admin.batches (
  unique_id VARCHAR(100) PRIMARY KEY,
  display_name VARCHAR(255),
  primary_teacher_id VARCHAR(255),
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  status VARCHAR(50) DEFAULT 'active'
);

-- Create batch_members table
CREATE TABLE lms_admin.batch_members (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id VARCHAR(100) REFERENCES lms_admin.batches(unique_id) ON DELETE CASCADE,
  student_id VARCHAR(255),
  added_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(batch_id, student_id)
);

-- Create batch_courses table
CREATE TABLE lms_admin.batch_courses (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id VARCHAR(100) REFERENCES lms_admin.batches(unique_id) ON DELETE CASCADE,
  course_id INTEGER,
  added_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(batch_id, course_id)
);

-- Create batch_classes table
CREATE TABLE lms_admin.batch_classes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id VARCHAR(100) REFERENCES lms_admin.batches(unique_id) ON DELETE CASCADE,
  course_id INTEGER,
  class_date_time TIMESTAMPTZ,
  primary_teacher_id VARCHAR(255),
  temporary_teacher_id VARCHAR(255),
  title VARCHAR(255),
  description TEXT,
  status VARCHAR(50) DEFAULT 'scheduled',
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Create batch_lesson_releases table
CREATE TABLE lms_admin.batch_lesson_releases (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id VARCHAR(100) REFERENCES lms_admin.batches(unique_id) ON DELETE CASCADE,
  lesson_id INTEGER,
  released_by VARCHAR(255),
  released_at TIMESTAMPTZ DEFAULT now(),
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(batch_id, lesson_id)
);

-- Create basic indexes
CREATE INDEX idx_batches_teacher_id ON lms_admin.batches(primary_teacher_id);
CREATE INDEX idx_batch_members_batch_id ON lms_admin.batch_members(batch_id);
CREATE INDEX idx_batch_courses_batch_id ON lms_admin.batch_courses(batch_id);
CREATE INDEX idx_batch_classes_batch_id ON lms_admin.batch_classes(batch_id);
