-- =============================================================================
-- Migration: Challenge lessons
-- File 27: external-challenge class type + student submissions
-- =============================================================================
--
-- A CHALLENGE is a third kind of class alongside Content and Quiz. The admin
-- points it at an external site (Scratch, Code.org, a GitHub task...); the
-- student does the work there, comes back, and submits a link to their result.
-- A teacher then approves it or sends it back for more work.
--
-- Design notes:
--  * The challenge itself is just a `lessons` row with lesson_type='challenge'.
--    It reuses `lesson_src` for the external URL and `description` for the
--    brief, so no column is added to `lessons` and every existing feature that
--    walks the curriculum (sorting, release gating, drip, the player sidebar)
--    keeps working with no change.
--  * Only the SUBMISSIONS need new storage, and they get their own table
--    mirroring assignment_submissions, which already solves the same shape.
--
-- Idempotent: safe to re-run.
-- =============================================================================

CREATE TABLE IF NOT EXISTS lms_admin.challenge_submissions (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- The lessons row (lesson_type='challenge') this answers.
  lesson_id     INTEGER     NOT NULL,
  -- Denormalised so teacher/admin queries can filter by course without a join.
  course_id     INTEGER,
  -- auth-service users.userId — an 11-digit STRING, not an int. Matches the
  -- convention in batch_members.user_id and assignment_submissions.user_id.
  user_id       VARCHAR(255) NOT NULL,
  -- The student's link to their finished work, and an optional note.
  submission_url  TEXT       NOT NULL,
  submission_note TEXT,
  -- submitted → the student has handed it in, awaiting review
  -- approved   → the teacher accepted it; THIS is what completes the lesson
  -- needs_work → sent back; the student may resubmit, which returns it to
  --              'submitted' rather than creating a second row
  status        VARCHAR(20) NOT NULL DEFAULT 'submitted',
  feedback      TEXT,
  reviewed_by   VARCHAR(255),
  reviewed_at   TIMESTAMPTZ,
  submitted_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- One submission per student per challenge. A resubmission UPDATES the row, so
-- a teacher never has to work out which of five rows is the current attempt.
CREATE UNIQUE INDEX IF NOT EXISTS uq_challenge_submission_lesson_user
  ON lms_admin.challenge_submissions (lesson_id, user_id);

-- The teacher's review queue reads "everything pending for this course".
CREATE INDEX IF NOT EXISTS idx_challenge_submissions_course_status
  ON lms_admin.challenge_submissions (course_id, status);

-- The student's player reads "my submission for this lesson".
CREATE INDEX IF NOT EXISTS idx_challenge_submissions_user
  ON lms_admin.challenge_submissions (user_id);

-- Guard the status vocabulary at the DB level: a typo in application code
-- would otherwise silently create a status nothing filters on, and such a
-- submission would vanish from both the student's view and the review queue.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.constraint_column_usage
     WHERE table_schema = 'lms_admin'
       AND table_name = 'challenge_submissions'
       AND constraint_name = 'challenge_submissions_status_chk'
  ) THEN
    ALTER TABLE lms_admin.challenge_submissions
      ADD CONSTRAINT challenge_submissions_status_chk
      CHECK (status IN ('submitted', 'approved', 'needs_work'));
  END IF;
END $$;
